apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zm9c2c5cz-dotnet-basic
  janus-idp.io/tekton: zm9c2c5cz-dotnet-basic
  backstage.io/kubernetes-id: zm9c2c5cz-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zm9c2c5cz-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
